/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sight;

import java.io.IOException;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

	public static void main(String[] args) {
		launch(args);
	}

	@Override
	public void start(Stage arg0) throws Exception {
		URL location = getClass().getClassLoader().getResource("ApplicationWindowV2.fxml");

		try {
			Parent root = FXMLLoader.load(location);
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setWidth(640);
			stage.setHeight(400);
			stage.setScene(scene);
			stage.show();
		} catch (IOException e) {
			e.printStackTrace();
		}        
	}
}
